# config/services.yaml

# ---------------------------------------------------
# Paramètres globaux de l'application
# ---------------------------------------------------
parameters:
    images_directory: '%kernel.project_dir%/public/uploads'  # dossier pour stocker les images uploadées

# ---------------------------------------------------
# Configuration par défaut des services
# ---------------------------------------------------
services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistre automatiquement les services comme commandes, event subscribers, etc.

    # Rendre toutes les classes dans src/ disponibles en tant que services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajouter ici d'autres services personnalisés si nécessaire
    # Remarque : les dernières définitions remplacent toujours les précédentes
